### ISSUE TITLE
Add World Border

### ISSUE THREAD

**Issue by NotActuallyTerry** [LoveTropics/meta#6]
"Me and my friends had a bit of fun exploring the chunks outside the desired/pre-made ones. Also loading too many new chunks can make the world file bigger and slightly longer reboots"

**Comment by Gegy** [comment]
@NotActuallyTerry Is this still in progress?

**Comment by NotActuallyTerry** [comment]
It is! I'm assuming for this to work, we'd need to apply a mod like [Dimensional Worldborder](https://www.curseforge.com/minecraft/mc-mods/dimensional-worldborder)

**Comment by NotActuallyTerry** [comment]
Found a 1.20 port at https://www.curseforge.com/minecraft/mc-mods/dimensional-worldborder-continuation, will be implementing

**Comment by NotActuallyTerry** [comment]
Added to server and tested by applying a 1000-wide border in Tropics, centering on spawn. Confirmed applied in Tropics but not applying to overworld.
